sudo: required
language: c

compiler:
    - gcc
    - clang

os:
    - linux
    - osx


addons:
    apt:
        - autoconf
	- automake
	- libtool
	- m4
	- libudev-dev

script:
    - ./autogen.sh && make -j4
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh --disable-udev && make -j4; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd Xcode && xcodebuild -project libusb.xcodeproj ; fi
