sudo: required
language: c

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq && sudo apt-get install -qq libudev-dev; fi

script:
    - ./autogen.sh && make -j4
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh --disable-udev && make -j4; fi
