sudo: required
language: c

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get install -qq libudev-dev ; fi

install:
    - ./autogen.sh
    - ./configure
    - make -j4
